### ISSUE TITLE
Rename?

### ISSUE THREAD

**Issue by jeff-h** [node-app/MacGapNode#3]
Hey — would you consider renaming this repo to MacGapNode or MacGapNodelike or something similar? I'm referring to it quite a bit over on https://github.com/maccman/macgap and it would lessen people's confusion if this had a different name, which explicitly described the difference.

A lot of people are interested in access to your node work inside MacGap so this is the correct place for those people to get their MacGap :)

**Comment by srijs** [comment]
Done :)

**Comment by jeff-h** [comment]
Awesome, thanks!
